package Cell;


/**
* Cell/ServerDBPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Wednesday, May 23, 2018 4:49:28 PM MSK
*/

public abstract class ServerDBPOA extends org.omg.PortableServer.Servant
 implements Cell.ServerDBOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerStation", new java.lang.Integer (0));
    _methods.put ("registerPhoneNumber", new java.lang.Integer (1));
    _methods.put ("sendSMS", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Cell/ServerDB/registerStation
       {
         Cell.Station objRef = Cell.StationHelper.read (in);
         String stationName = in.read_string ();
         int $result = (int)0;
         $result = this.registerStation (objRef, stationName);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Cell/ServerDB/registerPhoneNumber
       {
         String stationName = in.read_string ();
         String phoneNumber = in.read_string ();
         int $result = (int)0;
         $result = this.registerPhoneNumber (stationName, phoneNumber);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // Cell/ServerDB/sendSMS
       {
         String fromNum = in.read_string ();
         String toNum = in.read_string ();
         String message = in.read_string ();
         int $result = (int)0;
         $result = this.sendSMS (fromNum, toNum, message);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Cell/ServerDB:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServerDB _this() 
  {
    return ServerDBHelper.narrow(
    super._this_object());
  }

  public ServerDB _this(org.omg.CORBA.ORB orb) 
  {
    return ServerDBHelper.narrow(
    super._this_object(orb));
  }


} // class ServerDBPOA
