package Cell;


/**
* Cell/ServerDBOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Wednesday, May 23, 2018 4:49:28 PM MSK
*/

public interface ServerDBOperations 
{
  int registerStation (Cell.Station objRef, String stationName);
  int registerPhoneNumber (String stationName, String phoneNumber);
  int sendSMS (String fromNum, String toNum, String message);
} // interface ServerDBOperations
