package Cell;

/**
* Cell/ServerDBHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Wednesday, May 23, 2018 4:49:28 PM MSK
*/

public final class ServerDBHolder implements org.omg.CORBA.portable.Streamable
{
  public Cell.ServerDB value = null;

  public ServerDBHolder ()
  {
  }

  public ServerDBHolder (Cell.ServerDB initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Cell.ServerDBHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Cell.ServerDBHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Cell.ServerDBHelper.type ();
  }

}
