package Cell;


/**
* Cell/Station.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Wednesday, May 23, 2018 4:49:28 PM MSK
*/


/* Интерфейс базовой станции */
public interface Station extends StationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Station
