package Cell;


/**
* Cell/StationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Wednesday, May 23, 2018 4:49:28 PM MSK
*/


/* Интерфейс базовой станции */
public interface StationOperations 
{

  /* для обратного вызова трубки использовать ссылку TubeCallback */
  int register (Cell.TubeCallback objRef, String phoneNum);

  /* Отправить сообщение message от номера fromNum к номеру toNum */
  int sendSMSToDB (String fromNum, String toNum, String message);
  int sendSMSToTube (String fromNum, String toNum, String message);
  int setServerDBRef (Cell.ServerDB objRef);
  int setStationName (String stationName);
} // interface StationOperations
