package Cell;


/**
* Cell/StationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Wednesday, May 16, 2018 2:26:22 PM MSK
*/


/* Интерфейс базовой станции */
public interface StationOperations 
{

  /* для обратного вызова трубки использовать ссылку TubeCallback */
  int register (Cell.TubeCallback objRef, String phoneNum);

  /* Отправить сообщение message от номера fromNum к номеру toNum */
  int sendSMS (String fromNum, String toNum, String message);
} // interface StationOperations
