package Cell;


/**
* Cell/TubeCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Wednesday, May 23, 2018 4:49:28 PM MSK
*/

public interface TubeCallbackOperations 
{

  /* Принять сообщение message от номера fromNum */
  int sendSMS (String fromNum, String message);

  /* Вернуть свой номер */
  String getNum ();
} // interface TubeCallbackOperations
